# Generated by Django 4.2 on 2023-05-06 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flights.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
                ('generic_type', models.CharField(max_length=50, verbose_name='Тип ВС')),
            ],
            options={
                'verbose_name': 'Тип самолета',
                'verbose_name_plural': 'Типы самолетов',
                'unique_together': {('manufacturer', 'generic_type')},
            },
        ),
        migrations.CreateModel(
            name='Airframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Регистрационный номер')),
                ('photo', models.ImageField(upload_to=flights.models.Airframe.get_airframe_image_path, verbose_name='Фото ВС')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='airframes', to='flights.aircrafttype', verbose_name='Тип ВС')),
            ],
            options={
                'verbose_name': 'Воздушное судно',
                'verbose_name_plural': 'Воздушные судна',
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название авиакомпании')),
            ],
            options={
                'verbose_name': 'Авиакомпания',
                'verbose_name_plural': 'Авиакомпании',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50, verbose_name='Номер рейса')),
                ('date', models.DateField(verbose_name='Дата полета')),
                ('flight_time', models.TimeField(blank=True, null=True, verbose_name='Время полета')),
                ('airframe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.airframe', verbose_name='Воздушное судно')),
            ],
            options={
                'verbose_name': 'Совершенный полет',
                'verbose_name_plural': 'Совершенные полеты',
            },
        ),
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(blank=True, max_length=4, null=True, verbose_name='Место')),
                ('neighbors', models.TextField(blank=True, null=True, verbose_name='Соседи в полете')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена билета')),
                ('slug', models.SlugField(blank=True, verbose_name='Слаг')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight', verbose_name='Полет')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Путешествие пользователя',
                'verbose_name_plural': 'Путешествия пользователей',
            },
        ),
        migrations.CreateModel(
            name='TrackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_img', models.ImageField(blank=True, null=True, upload_to=flights.models.TrackImage.get_airframe_image_path, verbose_name='Изображение трэка')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_images', to='flights.usertrip', verbose_name='Полет пользователя')),
            ],
            options={
                'verbose_name': 'Изображения трэка',
                'verbose_name_plural': 'Изображения трэков',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.TextField(default='Вода', verbose_name='Предложенные напитки')),
                ('appertize', models.TextField(default='', verbose_name='Предложенные закуски')),
                ('main_course', models.TextField(default='', verbose_name='Основные блюда')),
                ('desert', models.TextField(default='', verbose_name='Предложенные десерты')),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена питания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=flights.models.Meal.get_airframe_image_path, verbose_name='Фотография питания')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_info', to='flights.flight', verbose_name='Полет')),
            ],
            options={
                'verbose_name': 'Питание в полете',
                'verbose_name_plural': 'Питание в полете',
            },
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Departure', 'Departure'), ('Arrival', 'Arrival')], max_length=20, verbose_name='Вылет/Прилет')),
                ('airport_code', models.CharField(max_length=4, verbose_name='IATA-код аэропорта')),
                ('metar', models.CharField(blank=True, max_length=200, null=True, verbose_name='METAR')),
                ('gate', models.CharField(blank=True, max_length=5, null=True, verbose_name='Гейт')),
                ('is_boarding_bridge', models.BooleanField(verbose_name='Через телетрап')),
                ('schedule_time', models.TimeField(blank=True, null=True, verbose_name='Время рассчетное')),
                ('actual_time', models.TimeField(blank=True, null=True, verbose_name='Время фактическое')),
                ('runway', models.CharField(max_length=3, verbose_name='Активная ВПП')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight', verbose_name='Полет')),
            ],
            options={
                'verbose_name': 'Дополнительная информация о полете',
                'verbose_name_plural': 'Дополнительная информация о полете',
            },
        ),
        migrations.AddField(
            model_name='airframe',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fleet', to='flights.airline', verbose_name='Авиакомпания'),
        ),
    ]
