# Generated by Django 4.2 on 2023-05-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight', verbose_name='Полет'),
        ),
        migrations.AlterField(
            model_name='trackimage',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.usertrip', verbose_name='Полет пользователя'),
        ),
    ]
