# Generated by Django 4.2 on 2023-05-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_meal_flight_alter_trackimage_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='flight',
        ),
        migrations.AddField(
            model_name='meal',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.usertrip', verbose_name='Путешествие'),
        ),
    ]
