# Generated by Django 4.2 on 2023-06-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_meal_flight_meal_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airframe',
            name='aircraft_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airframes', to='flights.aircrafttype', verbose_name='Тип ВС'),
        ),
        migrations.AlterField(
            model_name='airframe',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet', to='flights.airline', verbose_name='Авиакомпания'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airframe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.airframe', verbose_name='Воздушное судно'),
        ),
    ]
