# Generated by Django 4.2 on 2023-06-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airframe_aircraft_type_alter_airframe_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinfo',
            name='metar',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='METAR'),
        ),
    ]
