# Generated by Django 4.2 on 2023-07-07 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0005_alter_flightinfo_metar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airframe',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='flightinfo',
            unique_together={('flight', 'airport_code')},
        ),
        migrations.AlterUniqueTogether(
            name='usertrip',
            unique_together={('flight', 'passenger')},
        ),
    ]
