# Generated by Django 4.2 on 2023-07-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_airframe_serial_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='photo',
            new_name='meal_photo',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='price',
            new_name='meal_price',
        ),
    ]
