# Generated by Django 4.2 on 2023-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_rename_photo_meal_meal_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airframe',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterUniqueTogether(
            name='airframe',
            unique_together={('serial_number', 'registration_number')},
        ),
    ]
