# Generated by Django 4.2 on 2023-07-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_airframe_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airframe',
            name='registration_number',
            field=models.CharField(max_length=50, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='airframe',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Серийный номер'),
        ),
    ]
