# Generated by Django 4.2 on 2023-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_alter_airframe_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
    ]
